[Chapter2] ExpressJS
Alpha-ka-JS/YouTube pull request #2
Opened 2020-12-10 10:01 UTC by sungwon2054

## What does this PR do?

- express 실습 했습니다

## What was the difficult part of this PR?

- 이해하는데 많이 어려웠습니다. 많은 복습이 필요할듯 합니다

2020-12-10 14:41 UTC, LeeJehwan commented on JeongSungwon/.babelrc
> +}
add new line

2020-12-10 14:41 UTC, LeeJehwan commented on JeongSungwon/db.js
> +]
ditto

2020-12-10 14:41 UTC, LeeJehwan commented on JeongSungwon/db.js
> +
remove line

2020-12-10 14:43 UTC, LeeJehwan requested changes
전반적으로 현재 format이 안맞습니다. #1 에서 적용된 lint적용을 부탁드립니다.
(single quotation같은 부분들)

pug관련해서는 공백때문에 계속 경고가 나오는데 pug는 혹시 formatting 도구가없나요?

2020-12-10 14:44 UTC, LeeJehwan commented
라벨도달아주세요

2020-12-17 14:37 UTC, sungwon2054 commented
수정했습니다.
그리고 single quotation은 뒤에 가면 double이랑 섞어 쓰는 부분 있는걸로 기억하는데 풀면 안될까요?
그리고 아직 fetch를 하지 않아서 merge후에 lint-fix후 다시 PR 올리겠습니다

2020-12-17 14:44 UTC, LeeJehwan commented
> 수정했습니다.
> 그리고 single quotation은 뒤에 가면 double이랑 섞어 쓰는 부분 있는걸로 기억하는데 풀면 안될까요?
> 그리고 아직 fetch를 하지 않아서 merge후에 lint-fix후 다시 PR 올리겠습니다

그 섞어쓰는 부분까지 고려를 해서 lint가 되어있습니다.
class name은 double quotation, string은 single quotation같은 설정으로요.
혹시 그 외의 상황이 있으신가요?

2020-12-17 14:50 UTC, sungwon2054 commented
> 그 섞어쓰는 부분까지 고려를 해서 lint가 되어있습니다.
> class name은 double quotation, string은 single quotation같은 설정으로요.
> 혹시 그 외의 상황이 있으신가요?

그 외의 상황은 없던거 같습니다.

2020-12-17 14:53 UTC, LeeJehwan approved these changes
고생하셨습니다. 빠른시일내로 올려주세요

2020-12-17 14:54 UTC, merged